// Generated by gencpp from file crosbot_map/LoadSnaps.msg
// DO NOT EDIT!


#ifndef CROSBOT_MAP_MESSAGE_LOADSNAPS_H
#define CROSBOT_MAP_MESSAGE_LOADSNAPS_H

#include <ros/service_traits.h>


#include <crosbot_map/LoadSnapsRequest.h>
#include <crosbot_map/LoadSnapsResponse.h>


namespace crosbot_map
{

struct LoadSnaps
{

typedef LoadSnapsRequest Request;
typedef LoadSnapsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadSnaps
} // namespace crosbot_map


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crosbot_map::LoadSnaps > {
  static const char* value()
  {
    return "8666a8edc31971916e18761547a3684c";
  }

  static const char* value(const ::crosbot_map::LoadSnaps&) { return value(); }
};

template<>
struct DataType< ::crosbot_map::LoadSnaps > {
  static const char* value()
  {
    return "crosbot_map/LoadSnaps";
  }

  static const char* value(const ::crosbot_map::LoadSnaps&) { return value(); }
};


// service_traits::MD5Sum< ::crosbot_map::LoadSnapsRequest> should match 
// service_traits::MD5Sum< ::crosbot_map::LoadSnaps > 
template<>
struct MD5Sum< ::crosbot_map::LoadSnapsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_map::LoadSnaps >::value();
  }
  static const char* value(const ::crosbot_map::LoadSnapsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_map::LoadSnapsRequest> should match 
// service_traits::DataType< ::crosbot_map::LoadSnaps > 
template<>
struct DataType< ::crosbot_map::LoadSnapsRequest>
{
  static const char* value()
  {
    return DataType< ::crosbot_map::LoadSnaps >::value();
  }
  static const char* value(const ::crosbot_map::LoadSnapsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crosbot_map::LoadSnapsResponse> should match 
// service_traits::MD5Sum< ::crosbot_map::LoadSnaps > 
template<>
struct MD5Sum< ::crosbot_map::LoadSnapsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_map::LoadSnaps >::value();
  }
  static const char* value(const ::crosbot_map::LoadSnapsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_map::LoadSnapsResponse> should match 
// service_traits::DataType< ::crosbot_map::LoadSnaps > 
template<>
struct DataType< ::crosbot_map::LoadSnapsResponse>
{
  static const char* value()
  {
    return DataType< ::crosbot_map::LoadSnaps >::value();
  }
  static const char* value(const ::crosbot_map::LoadSnapsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CROSBOT_MAP_MESSAGE_LOADSNAPS_H
