// Generated by gencpp from file crosbot_msgs/StringArray.msg
// DO NOT EDIT!


#ifndef CROSBOT_MSGS_MESSAGE_STRINGARRAY_H
#define CROSBOT_MSGS_MESSAGE_STRINGARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crosbot_msgs
{
template <class ContainerAllocator>
struct StringArray_
{
  typedef StringArray_<ContainerAllocator> Type;

  StringArray_()
    : strings()  {
    }
  StringArray_(const ContainerAllocator& _alloc)
    : strings(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _strings_type;
  _strings_type strings;





  typedef boost::shared_ptr< ::crosbot_msgs::StringArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crosbot_msgs::StringArray_<ContainerAllocator> const> ConstPtr;

}; // struct StringArray_

typedef ::crosbot_msgs::StringArray_<std::allocator<void> > StringArray;

typedef boost::shared_ptr< ::crosbot_msgs::StringArray > StringArrayPtr;
typedef boost::shared_ptr< ::crosbot_msgs::StringArray const> StringArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crosbot_msgs::StringArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crosbot_msgs::StringArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crosbot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'crosbot_msgs': ['/home/azeng/turtle_ws/src/crosbot/crosbot_msgs/msg/geometry', '/home/azeng/turtle_ws/src/crosbot/crosbot_msgs/msg/controls', '/home/azeng/turtle_ws/src/crosbot/crosbot_msgs/msg/data']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_msgs::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_msgs::StringArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_msgs::StringArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_msgs::StringArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_msgs::StringArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_msgs::StringArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crosbot_msgs::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "51789d20146e565223d0963361aecda1";
  }

  static const char* value(const ::crosbot_msgs::StringArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x51789d20146e5652ULL;
  static const uint64_t static_value2 = 0x23d0963361aecda1ULL;
};

template<class ContainerAllocator>
struct DataType< ::crosbot_msgs::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crosbot_msgs/StringArray";
  }

  static const char* value(const ::crosbot_msgs::StringArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crosbot_msgs::StringArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] strings\n\
";
  }

  static const char* value(const ::crosbot_msgs::StringArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crosbot_msgs::StringArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.strings);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct StringArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crosbot_msgs::StringArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crosbot_msgs::StringArray_<ContainerAllocator>& v)
  {
    s << indent << "strings[]" << std::endl;
    for (size_t i = 0; i < v.strings.size(); ++i)
    {
      s << indent << "  strings[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.strings[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSBOT_MSGS_MESSAGE_STRINGARRAY_H
