(cl:defpackage crosbot_map-srv
  (:use )
  (:export
   "GETSNAP"
   "<GETSNAP-REQUEST>"
   "GETSNAP-REQUEST"
   "<GETSNAP-RESPONSE>"
   "GETSNAP-RESPONSE"
   "LISTSNAPS"
   "<LISTSNAPS-REQUEST>"
   "LISTSNAPS-REQUEST"
   "<LISTSNAPS-RESPONSE>"
   "LISTSNAPS-RESPONSE"
   "LOADSNAPS"
   "<LOADSNAPS-REQUEST>"
   "LOADSNAPS-REQUEST"
   "<LOADSNAPS-RESPONSE>"
   "LOADSNAPS-RESPONSE"
   "MODIFYSNAP"
   "<MODIFYSNAP-REQUEST>"
   "MODIFYSNAP-REQUEST"
   "<MODIFYSNAP-RESPONSE>"
   "MODIFYSNAP-RESPONSE"
  ))

