//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the crosbot_explore package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __crosbot_explore__CROSBOTASTARRECONFIGCONFIG_H__
#define __crosbot_explore__CROSBOTASTARRECONFIGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace crosbot_explore
{
  class CrosbotAStarReconfigConfigStatics;

  class CrosbotAStarReconfigConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(CrosbotAStarReconfigConfig &config, const CrosbotAStarReconfigConfig &max, const CrosbotAStarReconfigConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const CrosbotAStarReconfigConfig &config1, const CrosbotAStarReconfigConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, CrosbotAStarReconfigConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const CrosbotAStarReconfigConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CrosbotAStarReconfigConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const CrosbotAStarReconfigConfig &config) const = 0;
      virtual void getValue(const CrosbotAStarReconfigConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T CrosbotAStarReconfigConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (CrosbotAStarReconfigConfig::* field);

      virtual void clamp(CrosbotAStarReconfigConfig &config, const CrosbotAStarReconfigConfig &max, const CrosbotAStarReconfigConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const CrosbotAStarReconfigConfig &config1, const CrosbotAStarReconfigConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, CrosbotAStarReconfigConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const CrosbotAStarReconfigConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CrosbotAStarReconfigConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const CrosbotAStarReconfigConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const CrosbotAStarReconfigConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, CrosbotAStarReconfigConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, CrosbotAStarReconfigConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<CrosbotAStarReconfigConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(CrosbotAStarReconfigConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("weight_partial"==(*_i)->name){weight_partial = boost::any_cast<double>(val);}
        if("weight_expanded"==(*_i)->name){weight_expanded = boost::any_cast<double>(val);}
        if("weight_skeleton"==(*_i)->name){weight_skeleton = boost::any_cast<double>(val);}
        if("astar_voronoi_restricted"==(*_i)->name){astar_voronoi_restricted = boost::any_cast<double>(val);}
        if("astar_voronoi_partial"==(*_i)->name){astar_voronoi_partial = boost::any_cast<double>(val);}
        if("astar_voronoi_expand"==(*_i)->name){astar_voronoi_expand = boost::any_cast<double>(val);}
        if("astar_voronoi_orphanThreshold"==(*_i)->name){astar_voronoi_orphanThreshold = boost::any_cast<double>(val);}
      }
    }

    double weight_partial;
double weight_expanded;
double weight_skeleton;
double astar_voronoi_restricted;
double astar_voronoi_partial;
double astar_voronoi_expand;
double astar_voronoi_orphanThreshold;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double weight_partial;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double weight_expanded;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double weight_skeleton;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double astar_voronoi_restricted;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double astar_voronoi_partial;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double astar_voronoi_expand;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double astar_voronoi_orphanThreshold;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("CrosbotAStarReconfigConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const CrosbotAStarReconfigConfig &__max__ = __getMax__();
      const CrosbotAStarReconfigConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const CrosbotAStarReconfigConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const CrosbotAStarReconfigConfig &__getDefault__();
    static const CrosbotAStarReconfigConfig &__getMax__();
    static const CrosbotAStarReconfigConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const CrosbotAStarReconfigConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void CrosbotAStarReconfigConfig::ParamDescription<std::string>::clamp(CrosbotAStarReconfigConfig &config, const CrosbotAStarReconfigConfig &max, const CrosbotAStarReconfigConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class CrosbotAStarReconfigConfigStatics
  {
    friend class CrosbotAStarReconfigConfig;

    CrosbotAStarReconfigConfigStatics()
    {
CrosbotAStarReconfigConfig::GroupDescription<CrosbotAStarReconfigConfig::DEFAULT, CrosbotAStarReconfigConfig> Default("Default", "", 0, 0, true, &CrosbotAStarReconfigConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.weight_partial = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.weight_partial = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.weight_partial = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("weight_partial", "double", 0, "Partial region weighting", "", &CrosbotAStarReconfigConfig::weight_partial)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("weight_partial", "double", 0, "Partial region weighting", "", &CrosbotAStarReconfigConfig::weight_partial)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.weight_expanded = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.weight_expanded = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.weight_expanded = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("weight_expanded", "double", 0, "Expanded region weighting", "", &CrosbotAStarReconfigConfig::weight_expanded)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("weight_expanded", "double", 0, "Expanded region weighting", "", &CrosbotAStarReconfigConfig::weight_expanded)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.weight_skeleton = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.weight_skeleton = 1000.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.weight_skeleton = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("weight_skeleton", "double", 0, "Expanded region weighting", "", &CrosbotAStarReconfigConfig::weight_skeleton)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("weight_skeleton", "double", 0, "Expanded region weighting", "", &CrosbotAStarReconfigConfig::weight_skeleton)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.astar_voronoi_restricted = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.astar_voronoi_restricted = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.astar_voronoi_restricted = 0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("astar_voronoi_restricted", "double", 0, "Voronoi Constraint: Restricted", "", &CrosbotAStarReconfigConfig::astar_voronoi_restricted)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("astar_voronoi_restricted", "double", 0, "Voronoi Constraint: Restricted", "", &CrosbotAStarReconfigConfig::astar_voronoi_restricted)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.astar_voronoi_partial = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.astar_voronoi_partial = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.astar_voronoi_partial = 0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("astar_voronoi_partial", "double", 0, "Voronoi Constraint: Partial", "", &CrosbotAStarReconfigConfig::astar_voronoi_partial)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("astar_voronoi_partial", "double", 0, "Voronoi Constraint: Partial", "", &CrosbotAStarReconfigConfig::astar_voronoi_partial)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.astar_voronoi_expand = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.astar_voronoi_expand = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.astar_voronoi_expand = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("astar_voronoi_expand", "double", 0, "Voronoi Constraint: Expand", "", &CrosbotAStarReconfigConfig::astar_voronoi_expand)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("astar_voronoi_expand", "double", 0, "Voronoi Constraint: Expand", "", &CrosbotAStarReconfigConfig::astar_voronoi_expand)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.astar_voronoi_orphanThreshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.astar_voronoi_orphanThreshold = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.astar_voronoi_orphanThreshold = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("astar_voronoi_orphanThreshold", "double", 0, "Voronoi Constraint: Orphan Threshold", "", &CrosbotAStarReconfigConfig::astar_voronoi_orphanThreshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotAStarReconfigConfig::ParamDescription<double>("astar_voronoi_orphanThreshold", "double", 0, "Voronoi Constraint: Orphan Threshold", "", &CrosbotAStarReconfigConfig::astar_voronoi_orphanThreshold)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(CrosbotAStarReconfigConfig::AbstractGroupDescriptionConstPtr(new CrosbotAStarReconfigConfig::GroupDescription<CrosbotAStarReconfigConfig::DEFAULT, CrosbotAStarReconfigConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<CrosbotAStarReconfigConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<CrosbotAStarReconfigConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    CrosbotAStarReconfigConfig __max__;
    CrosbotAStarReconfigConfig __min__;
    CrosbotAStarReconfigConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const CrosbotAStarReconfigConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static CrosbotAStarReconfigConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &CrosbotAStarReconfigConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const CrosbotAStarReconfigConfig &CrosbotAStarReconfigConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const CrosbotAStarReconfigConfig &CrosbotAStarReconfigConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const CrosbotAStarReconfigConfig &CrosbotAStarReconfigConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<CrosbotAStarReconfigConfig::AbstractParamDescriptionConstPtr> &CrosbotAStarReconfigConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<CrosbotAStarReconfigConfig::AbstractGroupDescriptionConstPtr> &CrosbotAStarReconfigConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const CrosbotAStarReconfigConfigStatics *CrosbotAStarReconfigConfig::__get_statics__()
  {
    const static CrosbotAStarReconfigConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = CrosbotAStarReconfigConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CROSBOTASTARRECONFIGRECONFIGURATOR_H__
