//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the crosbot_explore package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __crosbot_explore__CROSBOTEXPLORERECONFIGCONFIG_H__
#define __crosbot_explore__CROSBOTEXPLORERECONFIGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace crosbot_explore
{
  class CrosbotExploreReconfigConfigStatics;

  class CrosbotExploreReconfigConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(CrosbotExploreReconfigConfig &config, const CrosbotExploreReconfigConfig &max, const CrosbotExploreReconfigConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const CrosbotExploreReconfigConfig &config1, const CrosbotExploreReconfigConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, CrosbotExploreReconfigConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const CrosbotExploreReconfigConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CrosbotExploreReconfigConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const CrosbotExploreReconfigConfig &config) const = 0;
      virtual void getValue(const CrosbotExploreReconfigConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T CrosbotExploreReconfigConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (CrosbotExploreReconfigConfig::* field);

      virtual void clamp(CrosbotExploreReconfigConfig &config, const CrosbotExploreReconfigConfig &max, const CrosbotExploreReconfigConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const CrosbotExploreReconfigConfig &config1, const CrosbotExploreReconfigConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, CrosbotExploreReconfigConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const CrosbotExploreReconfigConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, CrosbotExploreReconfigConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const CrosbotExploreReconfigConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const CrosbotExploreReconfigConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, CrosbotExploreReconfigConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, CrosbotExploreReconfigConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<CrosbotExploreReconfigConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(CrosbotExploreReconfigConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("voronoi_restricted"==(*_i)->name){voronoi_restricted = boost::any_cast<double>(val);}
        if("voronoi_partial"==(*_i)->name){voronoi_partial = boost::any_cast<double>(val);}
        if("voronoi_expand"==(*_i)->name){voronoi_expand = boost::any_cast<double>(val);}
        if("voronoi_orphanThreshold"==(*_i)->name){voronoi_orphanThreshold = boost::any_cast<double>(val);}
        if("min_travel_distance"==(*_i)->name){min_travel_distance = boost::any_cast<double>(val);}
        if("obstruction_angle"==(*_i)->name){obstruction_angle = boost::any_cast<double>(val);}
        if("proximity_angle"==(*_i)->name){proximity_angle = boost::any_cast<double>(val);}
        if("proximity_distance"==(*_i)->name){proximity_distance = boost::any_cast<double>(val);}
        if("skeleton_search_distance"==(*_i)->name){skeleton_search_distance = boost::any_cast<double>(val);}
        if("wall_search_distance"==(*_i)->name){wall_search_distance = boost::any_cast<double>(val);}
        if("wall_search_angle"==(*_i)->name){wall_search_angle = boost::any_cast<double>(val);}
        if("map_sub"==(*_i)->name){map_sub = boost::any_cast<std::string>(val);}
        if("drive_max_vel"==(*_i)->name){drive_max_vel = boost::any_cast<double>(val);}
        if("drive_max_turn"==(*_i)->name){drive_max_turn = boost::any_cast<double>(val);}
      }
    }

    double voronoi_restricted;
double voronoi_partial;
double voronoi_expand;
double voronoi_orphanThreshold;
double min_travel_distance;
double obstruction_angle;
double proximity_angle;
double proximity_distance;
double skeleton_search_distance;
double wall_search_distance;
double wall_search_angle;
std::string map_sub;
double drive_max_vel;
double drive_max_turn;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double voronoi_restricted;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double voronoi_partial;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double voronoi_expand;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double voronoi_orphanThreshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double min_travel_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double obstruction_angle;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double proximity_angle;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double proximity_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double skeleton_search_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wall_search_distance;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double wall_search_angle;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      std::string map_sub;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double drive_max_vel;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double drive_max_turn;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("CrosbotExploreReconfigConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const CrosbotExploreReconfigConfig &__max__ = __getMax__();
      const CrosbotExploreReconfigConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const CrosbotExploreReconfigConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const CrosbotExploreReconfigConfig &__getDefault__();
    static const CrosbotExploreReconfigConfig &__getMax__();
    static const CrosbotExploreReconfigConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const CrosbotExploreReconfigConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void CrosbotExploreReconfigConfig::ParamDescription<std::string>::clamp(CrosbotExploreReconfigConfig &config, const CrosbotExploreReconfigConfig &max, const CrosbotExploreReconfigConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class CrosbotExploreReconfigConfigStatics
  {
    friend class CrosbotExploreReconfigConfig;

    CrosbotExploreReconfigConfigStatics()
    {
CrosbotExploreReconfigConfig::GroupDescription<CrosbotExploreReconfigConfig::DEFAULT, CrosbotExploreReconfigConfig> Default("Default", "", 0, 0, true, &CrosbotExploreReconfigConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.voronoi_restricted = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.voronoi_restricted = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.voronoi_restricted = 0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("voronoi_restricted", "double", 0, "Voronoi Constraint: Restricted", "", &CrosbotExploreReconfigConfig::voronoi_restricted)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("voronoi_restricted", "double", 0, "Voronoi Constraint: Restricted", "", &CrosbotExploreReconfigConfig::voronoi_restricted)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.voronoi_partial = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.voronoi_partial = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.voronoi_partial = 0.2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("voronoi_partial", "double", 0, "Voronoi Constraint: Partial", "", &CrosbotExploreReconfigConfig::voronoi_partial)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("voronoi_partial", "double", 0, "Voronoi Constraint: Partial", "", &CrosbotExploreReconfigConfig::voronoi_partial)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.voronoi_expand = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.voronoi_expand = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.voronoi_expand = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("voronoi_expand", "double", 0, "Voronoi Constraint: Expand", "", &CrosbotExploreReconfigConfig::voronoi_expand)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("voronoi_expand", "double", 0, "Voronoi Constraint: Expand", "", &CrosbotExploreReconfigConfig::voronoi_expand)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.voronoi_orphanThreshold = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.voronoi_orphanThreshold = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.voronoi_orphanThreshold = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("voronoi_orphanThreshold", "double", 0, "Voronoi Constraint: Orphan Threshold", "", &CrosbotExploreReconfigConfig::voronoi_orphanThreshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("voronoi_orphanThreshold", "double", 0, "Voronoi Constraint: Orphan Threshold", "", &CrosbotExploreReconfigConfig::voronoi_orphanThreshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_travel_distance = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_travel_distance = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_travel_distance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("min_travel_distance", "double", 0, "Minimum travel distance for wall following target", "", &CrosbotExploreReconfigConfig::min_travel_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("min_travel_distance", "double", 0, "Minimum travel distance for wall following target", "", &CrosbotExploreReconfigConfig::min_travel_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.obstruction_angle = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.obstruction_angle = 360.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.obstruction_angle = 45.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("obstruction_angle", "double", 0, "Angle to deviate by to consider that a path is blocked (in degrees)", "", &CrosbotExploreReconfigConfig::obstruction_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("obstruction_angle", "double", 0, "Angle to deviate by to consider that a path is blocked (in degrees)", "", &CrosbotExploreReconfigConfig::obstruction_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.proximity_angle = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.proximity_angle = 360.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.proximity_angle = 20.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("proximity_angle", "double", 0, "Proximity Angle to define when the robot is 'at the goal' (in degrees)", "", &CrosbotExploreReconfigConfig::proximity_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("proximity_angle", "double", 0, "Proximity Angle to define when the robot is 'at the goal' (in degrees)", "", &CrosbotExploreReconfigConfig::proximity_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.proximity_distance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.proximity_distance = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.proximity_distance = 0.5;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("proximity_distance", "double", 0, "Proximity Distance to define when the robot is 'at the goal'", "", &CrosbotExploreReconfigConfig::proximity_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("proximity_distance", "double", 0, "Proximity Distance to define when the robot is 'at the goal'", "", &CrosbotExploreReconfigConfig::proximity_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.skeleton_search_distance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.skeleton_search_distance = 3.14159;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.skeleton_search_distance = 1.570795;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("skeleton_search_distance", "double", 0, "Skeleton Search Distance", "", &CrosbotExploreReconfigConfig::skeleton_search_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("skeleton_search_distance", "double", 0, "Skeleton Search Distance", "", &CrosbotExploreReconfigConfig::skeleton_search_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wall_search_distance = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wall_search_distance = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wall_search_distance = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("wall_search_distance", "double", 0, "Wall Search Distance", "", &CrosbotExploreReconfigConfig::wall_search_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("wall_search_distance", "double", 0, "Wall Search Distance", "", &CrosbotExploreReconfigConfig::wall_search_distance)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.wall_search_angle = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.wall_search_angle = 3.14159;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.wall_search_angle = 1.570795;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("wall_search_angle", "double", 0, "Wall Search Angle", "", &CrosbotExploreReconfigConfig::wall_search_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("wall_search_angle", "double", 0, "Wall Search Angle", "", &CrosbotExploreReconfigConfig::wall_search_angle)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.map_sub = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.map_sub = "";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.map_sub = "map";
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<std::string>("map_sub", "str", 0, "Map Sub Topic", "", &CrosbotExploreReconfigConfig::map_sub)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<std::string>("map_sub", "str", 0, "Map Sub Topic", "", &CrosbotExploreReconfigConfig::map_sub)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.drive_max_vel = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.drive_max_vel = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.drive_max_vel = 0.3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("drive_max_vel", "double", 0, "Voronoi Constraint: Expand", "", &CrosbotExploreReconfigConfig::drive_max_vel)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("drive_max_vel", "double", 0, "Voronoi Constraint: Expand", "", &CrosbotExploreReconfigConfig::drive_max_vel)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.drive_max_turn = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.drive_max_turn = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.drive_max_turn = 0.3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("drive_max_turn", "double", 0, "Voronoi Constraint: Expand", "", &CrosbotExploreReconfigConfig::drive_max_turn)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr(new CrosbotExploreReconfigConfig::ParamDescription<double>("drive_max_turn", "double", 0, "Voronoi Constraint: Expand", "", &CrosbotExploreReconfigConfig::drive_max_turn)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(CrosbotExploreReconfigConfig::AbstractGroupDescriptionConstPtr(new CrosbotExploreReconfigConfig::GroupDescription<CrosbotExploreReconfigConfig::DEFAULT, CrosbotExploreReconfigConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<CrosbotExploreReconfigConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<CrosbotExploreReconfigConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    CrosbotExploreReconfigConfig __max__;
    CrosbotExploreReconfigConfig __min__;
    CrosbotExploreReconfigConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const CrosbotExploreReconfigConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static CrosbotExploreReconfigConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &CrosbotExploreReconfigConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const CrosbotExploreReconfigConfig &CrosbotExploreReconfigConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const CrosbotExploreReconfigConfig &CrosbotExploreReconfigConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const CrosbotExploreReconfigConfig &CrosbotExploreReconfigConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<CrosbotExploreReconfigConfig::AbstractParamDescriptionConstPtr> &CrosbotExploreReconfigConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<CrosbotExploreReconfigConfig::AbstractGroupDescriptionConstPtr> &CrosbotExploreReconfigConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const CrosbotExploreReconfigConfigStatics *CrosbotExploreReconfigConfig::__get_statics__()
  {
    const static CrosbotExploreReconfigConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = CrosbotExploreReconfigConfigStatics::get_instance();

    return statics;
  }


}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __CROSBOTEXPLORERECONFIGRECONFIGURATOR_H__
