// Generated by gencpp from file crosbot_explore/SetExplorerModeResponse.msg
// DO NOT EDIT!


#ifndef CROSBOT_EXPLORE_MESSAGE_SETEXPLORERMODERESPONSE_H
#define CROSBOT_EXPLORE_MESSAGE_SETEXPLORERMODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace crosbot_explore
{
template <class ContainerAllocator>
struct SetExplorerModeResponse_
{
  typedef SetExplorerModeResponse_<ContainerAllocator> Type;

  SetExplorerModeResponse_()
    : id(0)
    , success(false)  {
    }
  SetExplorerModeResponse_(const ContainerAllocator& _alloc)
    : id(0)
    , success(false)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetExplorerModeResponse_

typedef ::crosbot_explore::SetExplorerModeResponse_<std::allocator<void> > SetExplorerModeResponse;

typedef boost::shared_ptr< ::crosbot_explore::SetExplorerModeResponse > SetExplorerModeResponsePtr;
typedef boost::shared_ptr< ::crosbot_explore::SetExplorerModeResponse const> SetExplorerModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace crosbot_explore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'crosbot_explore': ['/home/azeng/turtle_ws/src/crosbot/crosbot_explore/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66bd0af842fb92973ccdf03282b43412";
  }

  static const char* value(const ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66bd0af842fb9297ULL;
  static const uint64_t static_value2 = 0x3ccdf03282b43412ULL;
};

template<class ContainerAllocator>
struct DataType< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "crosbot_explore/SetExplorerModeResponse";
  }

  static const char* value(const ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
int32 id\n\
\n\
\n\
bool success\n\
";
  }

  static const char* value(const ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetExplorerModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::crosbot_explore::SetExplorerModeResponse_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CROSBOT_EXPLORE_MESSAGE_SETEXPLORERMODERESPONSE_H
