// Generated by gencpp from file crosbot_explore/SetExplorerMode.msg
// DO NOT EDIT!


#ifndef CROSBOT_EXPLORE_MESSAGE_SETEXPLORERMODE_H
#define CROSBOT_EXPLORE_MESSAGE_SETEXPLORERMODE_H

#include <ros/service_traits.h>


#include <crosbot_explore/SetExplorerModeRequest.h>
#include <crosbot_explore/SetExplorerModeResponse.h>


namespace crosbot_explore
{

struct SetExplorerMode
{

typedef SetExplorerModeRequest Request;
typedef SetExplorerModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetExplorerMode
} // namespace crosbot_explore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::crosbot_explore::SetExplorerMode > {
  static const char* value()
  {
    return "9ccc9bf7742b96feab802ba5adb527a6";
  }

  static const char* value(const ::crosbot_explore::SetExplorerMode&) { return value(); }
};

template<>
struct DataType< ::crosbot_explore::SetExplorerMode > {
  static const char* value()
  {
    return "crosbot_explore/SetExplorerMode";
  }

  static const char* value(const ::crosbot_explore::SetExplorerMode&) { return value(); }
};


// service_traits::MD5Sum< ::crosbot_explore::SetExplorerModeRequest> should match 
// service_traits::MD5Sum< ::crosbot_explore::SetExplorerMode > 
template<>
struct MD5Sum< ::crosbot_explore::SetExplorerModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_explore::SetExplorerMode >::value();
  }
  static const char* value(const ::crosbot_explore::SetExplorerModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_explore::SetExplorerModeRequest> should match 
// service_traits::DataType< ::crosbot_explore::SetExplorerMode > 
template<>
struct DataType< ::crosbot_explore::SetExplorerModeRequest>
{
  static const char* value()
  {
    return DataType< ::crosbot_explore::SetExplorerMode >::value();
  }
  static const char* value(const ::crosbot_explore::SetExplorerModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::crosbot_explore::SetExplorerModeResponse> should match 
// service_traits::MD5Sum< ::crosbot_explore::SetExplorerMode > 
template<>
struct MD5Sum< ::crosbot_explore::SetExplorerModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::crosbot_explore::SetExplorerMode >::value();
  }
  static const char* value(const ::crosbot_explore::SetExplorerModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::crosbot_explore::SetExplorerModeResponse> should match 
// service_traits::DataType< ::crosbot_explore::SetExplorerMode > 
template<>
struct DataType< ::crosbot_explore::SetExplorerModeResponse>
{
  static const char* value()
  {
    return DataType< ::crosbot_explore::SetExplorerMode >::value();
  }
  static const char* value(const ::crosbot_explore::SetExplorerModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CROSBOT_EXPLORE_MESSAGE_SETEXPLORERMODE_H
