(cl:defpackage crosbot_explore-srv
  (:use )
  (:export
   "GETPATH"
   "<GETPATH-REQUEST>"
   "GETPATH-REQUEST"
   "<GETPATH-RESPONSE>"
   "GETPATH-RESPONSE"
   "SETEXPLORERMODE"
   "<SETEXPLORERMODE-REQUEST>"
   "SETEXPLORERMODE-REQUEST"
   "<SETEXPLORERMODE-RESPONSE>"
   "SETEXPLORERMODE-RESPONSE"
  ))

